### ISSUE TITLE
Changes in dashboard.models.py

### ISSUE THREAD

**Issue by dhruvhacks** [singhsourabh/Night-Stalker#3]
https://github.com/singhsourabh/assessment/blob/3ca63d562d00aabcbca859a7a1ad1a97a1aedf8f/dashboard/models.py#L3
Change the ```User``` model name to ```UserDetails``` since django uses ```django.contrib.auth.models.Users``` for storing user data for authentication purposes and you are using this model in your project by including ```django.contrib.auth.urls```

**Comment by singhsourabh** [comment]
done
